services:
  - type: web
    name: hospital-capacity-api
    env: python
    buildCommand: pip install -r requirements.txt
    workingDirectory: hospital_data_api
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    plan: free
