services:
  - type: web
    name: hospital-capacity-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app --bind 0.0.0.0:$PORT
    plan: free

