services:
  - type: web
    name: hospital-capacity-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_data_api.api.index:app --bind 0.0.0.0:$PORT
    workingDirectory: /opt/render/project/src/hospital_data_api  # Set this to the correct path
    plan: free
